name: Bug report
description: Report a bug or error, providing details about the issue, steps to reproduce, and your environment setup.
labels: ['Triage']
type: 'Bug'
body:
- type: input
  attributes:
    label: Tempest version
    description: Provide the Tempest version that you are using.
    value: 3.0
  validations:
    required: true
- type: dropdown
  attributes:
    label: PHP version
    description: Provide the PHP version that you are using.
    options: ['8.4', '8.5']
    multiple: true
  validations:
    required: true
- type: dropdown
  attributes:
    label: Operating system
    description: Provide the operating system that you are using.
    options: ['Linux', 'macOS', 'Windows', 'Other']
    multiple: true
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Please provide a detailed description of the issue you are running into.
  validations:
    required: true
